### ISSUE TITLE
Allure @Step annotation does not work with groovy/spock code

### ISSUE THREAD

**Issue by ysparrow** [allure-framework/allure-spock-adaptor#10]
I'm using spock framework and groovy for my tests. Also I'm using allure-spock-1.0-adaptor for generating Allure reports. Reports looks fine, but not showing steps in results. All groovy methods are annotated with @Step but still not logged in report.

**Comment by ysparrow** [comment]
Not an issue anymore. Since there are no example of how to use spock-adaptor ( https://github.com/allure-examples/allure-spock-example ) this is not obvious that it reqire allure-junit-adaptor inline with allure-spock-adaptor to have @Steps logged into report. Solved by adding dependency for allure-junit-adaptor and properly set-up aspectjweaver the same way as it is in allure-junit example.

**Comment by m-shahid** [comment]
@ysparrow Can please help me. I am also facing the same issue. I have added junit adaptor and aspectjweaver as shown at [https://github.com/allure-examples/allure-gradle-junit-example/blob/master/build.gradle] but still i am not able to view steps in allure reports.

**Comment by ysparrow** [comment]
@mshahidsayyad here is my example for gradle build:
https://github.com/ysparrow/groovy-test-for-rest/blob/master/build.gradle

**Comment by tanjaduro** [comment]
What to do for integration Spock + Maven + Allure2? I can't see @Step annotation output in Allure reports
