### ISSUE TITLE
Misc typos

### ISSUE THREAD

**Issue by php-coder** [allure-framework/allure-spock-adaptor#4]
I believe that [there](https://github.com/allure-framework/allure-spock-adaptor/blob/master/spock-1.0/src/test/groovy/ru/yandex/qatools/allure/spock/testdata/SimpleAnnotatedSpecification.groovy#L10) is a typo: s/sock/spock/

**Comment by vania-pooh** [comment]
Any pull requests to fix this one? :)

**Comment by php-coder** [comment]
Give me a few minutes :)

**Comment by php-coder** [comment]
I've fixed this one and found&fixed a couple more.
