### ISSUE TITLE
Release Allure Spock Adaptor into Maven Central

### ISSUE THREAD

**Issue by ctapobep** [allure-framework/allure-spock-adaptor#6]
If the framework is ready to be used in tests, would be great to have it released into the Central.

**Comment by vania-pooh** [comment]
I'm not sure if it's possible to release Maven project with snapshot dependencies (Spock is snapshot). Need to specify spock releases.

**Comment by ctapobep** [comment]
There are non-snapshot spock dependencies:
```xml
      <dependency>
        <groupId>org.spockframework</groupId>
        <artifactId>spock-core</artifactId>
        <version>1.0-groovy-2.4</version>
        <scope>test</scope>
      </dependency>
```

**Comment by vania-pooh** [comment]
Please send a PR and let's do that.

**Comment by ctapobep** [comment]
So.. the PR is merged, shall we proceed with releasing?

**Comment by baev** [comment]
@ctapobep adaptor released as well, should be available in Maven Central in a few hours.
